### ISSUE TITLE
Bug on `/user/login`

### ISSUE THREAD

**Issue by Prev** [ratchetcloud/forums-backend#1]
When post wrong `password` with *existing* `username`, it returns `{"message":"Authentication failed."}` with 401, but when post *non-existing* `username`, returns 500 Internal Server Error.

Problem by below code.

```js
User.findOne({ name: req.body.username })
        .exec()
        .then(user => {
            if (user.length < 1) {
                return res.status(401).json({ message: "Authentication failed." });
            }
            <... JWT validation ...>

        .catch(err => {
            res.status(500).json({ error: err });
        });
```
I guess `mongoose.model.findOne` raise error if there is no object found.
Researching and fixing required.

**Comment by liangl1412** [comment]
correct, you just need give some readable message to user in the catch block, you can either do "message: "Authentication failed."" or "user is not exist, do you want create one" etc
